#include <cuda_runtime.h>

#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <cassert>
#include <cmath>
#include <memory>
#include <stdexcept>
#include <vector>

#include "cuda_utils.h"
#include "tensor.h"

// Not a good way to compare floats, it doesn't take scale into account...
// but good enough for us right now because all our values are O(1).
#define ASSERT_ALMOST_EQUAL(lhs, rhs) assert(std::abs((lhs) - (rhs)) < 0.0001);

size_t cuda_mem_free() {
	size_t mem_free, mem_total;
	CUDA_CHECK(cudaMemGetInfo(&mem_free, &mem_total));
	return mem_free;
}

FloatTensor make_sequential_tensor(std::vector<size_t> shape, Device dev) {
	FloatTensor t = FloatTensor::zeros(shape, dev);
	for (size_t i = 0; i < t.numel(); i++) {
		t.set_raw_idx(i, static_cast<float>(i + 1));
	}
	return t;
}

FloatTensor make_noncontiguous_tensor(Device dev) {
	FloatTensor base = make_sequential_tensor({3, 4}, dev);
	return base.view_raw({3, 4}, 0, {1, 3});
}

void assert_raw_values(FloatTensor t, std::vector<float> expected) {
	assert(t.is_contiguous());
	assert(t.numel() == expected.size());
	for (size_t i = 0; i < expected.size(); i++) {
		ASSERT_ALMOST_EQUAL(t.get_raw_idx(i), expected[i]);
	}
}

void assert_same_logical_values_recursive(FloatTensor &lhs, FloatTensor &rhs,
	                                      std::vector<ssize_t> &coords,
	                                      size_t dim) {
	if (dim == lhs.shape_.size()) {
		ASSERT_ALMOST_EQUAL(lhs.get_idx(LogicalIndex{coords}),
		                    rhs.get_idx(LogicalIndex{coords}));
		return;
	}

	for (size_t i = 0; i < lhs.shape_[dim]; i++) {
		coords[dim] = static_cast<ssize_t>(i);
		assert_same_logical_values_recursive(lhs, rhs, coords, dim + 1);
	}
}

void assert_same_logical_values(FloatTensor lhs, FloatTensor rhs) {
	assert(lhs.shape_ == rhs.shape_);
	std::vector<ssize_t> coords(lhs.shape_.size(), 0);
	assert_same_logical_values_recursive(lhs, rhs, coords, 0);
}

void test_tensor_constructor() {
	FloatTensor t = FloatTensor::zeros_1d(10);
	float x = t.get_raw_idx(3);
	assert(x == 0.0f);
	return;
}

void test_value_assignment() {
	FloatTensor t = FloatTensor::zeros_1d(10);
	float val = 2.42;
	t.set_raw_idx(3, val);
	float should_be_val = t.get_raw_idx(3);
	assert(should_be_val == val);
	return;
}

void test_move() {
	FloatTensor t = FloatTensor::zeros_1d(2);
	t.set_raw_idx(0, 1.23);
	t.set_raw_idx(1, 4.56);

	t.move_to_device(Device::GPU);
	t.set_raw_idx(0, 2.34);
	float val0 = t.get_raw_idx(0);
	float val1 = t.get_raw_idx(1);
	ASSERT_ALMOST_EQUAL(val0, 2.34);
	ASSERT_ALMOST_EQUAL(val1, 4.56);

	t.move_to_device(Device::CPU);
	float val2 = t.get_raw_idx(0);
	float val3 = t.get_raw_idx(1);
	ASSERT_ALMOST_EQUAL(val2, 2.34);
	ASSERT_ALMOST_EQUAL(val3, 4.56);
	return;
}

void test_memory_not_wasted() {
	CUDA_CHECK(cudaGetLastError());
	CUDA_CHECK(cudaDeviceSynchronize());
	FloatTensor t = FloatTensor::zeros_1d(1000000);  // use lots of memory
	size_t mem_before = cuda_mem_free();
	t.move_to_device(Device::GPU);
	size_t mem_during = cuda_mem_free();
	t.move_to_device(Device::CPU);
	size_t mem_after = cuda_mem_free();
	assert(mem_after > mem_during);
	assert(mem_after == mem_before);
	return;
}

void test_copy_mutability() {
	FloatTensor t1 = FloatTensor::zeros_1d(2);
	FloatTensor t2 = t1;
	t1.set_raw_idx(0, 1.1);
	t2.set_raw_idx(1, 2.2);

	assert(t1.block_ == t2.block_);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(0), 1.1);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(1), 2.2);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(0), 1.1);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(1), 2.2);

	return;
}

void test_clone_mutability() {
	FloatTensor t1 = FloatTensor::zeros_1d(2);
	t1.set_raw_idx(0, 1.1);

	FloatTensor t2 = t1.clone();
	t2.set_raw_idx(1, 2.2);

	t1.set_raw_idx(0, 3.3);

	assert(t1.block_ != t2.block_);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(0), 3.3);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(1), 0.0);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(0), 1.1);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(1), 2.2);
	return;
}

// =========== TESTS GENERATED BY AI AGENTS ===========
void test_view_shapes_strides_and_aliasing() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);

	FloatTensor flat = base.view({12});
	assert(flat.dim_ == 1);
	assert(flat.shape_ == std::vector<size_t>({12}));
	assert(flat.strides_ == std::vector<ssize_t>({1}));
	assert(flat.block_ == base.block_);
	assert(flat.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(flat.get_idx(LogicalIndex{{6}}),
	                    base.get_idx(LogicalIndex{{1, 2}}));

	FloatTensor row = base.view({1, 12});
	assert(row.dim_ == 2);
	assert(row.shape_ == std::vector<size_t>({1, 12}));
	assert(row.strides_ == std::vector<ssize_t>({12, 1}));
	assert(row.block_ == base.block_);
	assert(row.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(row.get_idx(LogicalIndex{{0, 6}}),
	                    base.get_idx(LogicalIndex{{1, 2}}));

	FloatTensor reshaped = base.view({4, 3});
	assert(reshaped.dim_ == 2);
	assert(reshaped.shape_ == std::vector<size_t>({4, 3}));
	assert(reshaped.strides_ == std::vector<ssize_t>({3, 1}));
	assert(reshaped.block_ == base.block_);
	assert(reshaped.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(reshaped.get_idx(LogicalIndex{{2, 0}}),
	                    base.get_idx(LogicalIndex{{1, 2}}));
}

void test_view_of_view() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	FloatTensor first = base.view({1, 12});
	FloatTensor second = first.view({3, 4});

	assert(first.shape_ == std::vector<size_t>({1, 12}));
	assert(first.strides_ == std::vector<ssize_t>({12, 1}));
	assert(second.shape_ == std::vector<size_t>({3, 4}));
	assert(second.strides_ == std::vector<ssize_t>({4, 1}));
	assert(first.block_ == base.block_);
	assert(second.block_ == base.block_);
	assert(second.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(second.get_idx(LogicalIndex{{2, 3}}),
	                    base.get_idx(LogicalIndex{{2, 3}}));

	FloatTensor third = first.view({12});
	assert(third.shape_ == std::vector<size_t>({12}));
	assert(third.strides_ == std::vector<ssize_t>({1}));
	assert(third.block_ == base.block_);
	ASSERT_ALMOST_EQUAL(third.get_idx(LogicalIndex{{11}}),
	                    base.get_idx(LogicalIndex{{2, 3}}));
}

void test_view_memory_management() {
	std::weak_ptr<FloatBlock> weak_block;
	std::unique_ptr<FloatTensor> last_view;

	{
		FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
		weak_block = base.block_;
		assert(base.block_.use_count() == 1);

		FloatTensor view1 = base.view({12});
		FloatTensor view2 = base.view({4, 3});
		assert(base.block_ == view1.block_);
		assert(base.block_ == view2.block_);
		assert(base.data_ptr() == view1.data_ptr());
		assert(base.data_ptr() == view2.data_ptr());
		assert(base.block_.use_count() == 3);

		last_view = std::make_unique<FloatTensor>(view2);
		assert(base.block_.use_count() == 4);
		ASSERT_ALMOST_EQUAL(last_view->get_idx(LogicalIndex{{2, 0}}),
		                    base.get_idx(LogicalIndex{{1, 2}}));
	}

	assert(!weak_block.expired());
	assert(last_view);
	assert(last_view->block_.use_count() == 1);
	float still_there = last_view->get_idx(LogicalIndex{{2, 0}});
	assert(std::isfinite(still_there));

	last_view.reset();
	assert(weak_block.expired());
}

void test_view_rejects_multiple_negative_one() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	bool threw = false;
	try {
		base.view({-1, -1});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_view_rejects_zero_and_negative_dims() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);

	bool threw_zero = false;
	try {
		base.view({0, 12});
	} catch (const std::invalid_argument&) {
		threw_zero = true;
	}
	assert(threw_zero);

	bool threw_negative = false;
	try {
		base.view({-2, 6});
	} catch (const std::invalid_argument&) {
		threw_negative = true;
	}
	assert(threw_negative);
}

void test_view_rejects_invalid_numel() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	bool threw = false;
	try {
		base.view({5, 5});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_view_rejects_noncontiguous_tensor() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	FloatTensor noncontig = base.view_raw({3, 4}, 0, {1, 3});
	assert(!noncontig.is_contiguous());

	bool threw = false;
	try {
		noncontig.view({12});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_contiguous_clone_preserves_shape_and_values(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev);
	FloatTensor cloned = source.contiguous_clone();

	assert(cloned.shape_ == source.shape_);
	assert(cloned.is_contiguous());
	assert(cloned.block_ != source.block_);
	assert_same_logical_values(source, cloned);
	assert_raw_values(cloned, {1.0f, 4.0f, 7.0f, 10.0f,
	                          2.0f, 5.0f, 8.0f, 11.0f,
	                          3.0f, 6.0f, 9.0f, 12.0f});
}

void test_contiguous_clone_breaks_aliasing(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev);
	FloatTensor cloned = source.contiguous_clone();

	cloned.set_idx(LogicalIndex{{1, 2}}, 1234.5f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 2}}), 8.0f);
	ASSERT_ALMOST_EQUAL(cloned.get_idx(LogicalIndex{{1, 2}}), 1234.5f);
}

void test_reshape_contiguous_matches_flat_order(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3}, dev);
	FloatTensor reshaped = source.reshape({3, 2});

	assert(reshaped.shape_ == std::vector<size_t>({3, 2}));
	assert(reshaped.is_contiguous());
	assert(reshaped.block_ != source.block_);
	assert_raw_values(reshaped, {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f});
}

void test_reshape_noncontiguous_matches_contiguous_clone_then_reshape(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev);
	FloatTensor reshaped = source.reshape({2, 6});
	FloatTensor expected = source.contiguous_clone().reshape({2, 6});

	assert(reshaped.shape_ == std::vector<size_t>({2, 6}));
	assert(reshaped.is_contiguous());
	assert(reshaped.block_ != source.block_);
	assert_same_logical_values(expected, reshaped);
	assert_raw_values(reshaped, {1.0f, 4.0f, 7.0f, 10.0f, 2.0f, 5.0f,
	                            8.0f, 11.0f, 3.0f, 6.0f, 9.0f, 12.0f});
}

void test_reshape_infers_negative_one(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev);
	FloatTensor reshaped = source.reshape({3, -1});

	assert(reshaped.shape_ == std::vector<size_t>({3, 4}));
	assert(reshaped.is_contiguous());
	assert_raw_values(reshaped, {1.0f, 4.0f, 7.0f, 10.0f,
	                            2.0f, 5.0f, 8.0f, 11.0f,
	                            3.0f, 6.0f, 9.0f, 12.0f});
}

void test_reshape_always_copies_even_for_contiguous_tensor(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3}, dev);
	FloatTensor reshaped = source.reshape({1, 6});

	assert(reshaped.shape_ == std::vector<size_t>({1, 6}));
	assert(reshaped.is_contiguous());
	assert(reshaped.block_ != source.block_);
	assert(reshaped.data_ptr() != source.data_ptr());
	ASSERT_ALMOST_EQUAL(reshaped.get_idx(LogicalIndex{{0, 4}}),
	                    source.get_idx(LogicalIndex{{1, 1}}));

	reshaped.set_idx(LogicalIndex{{0, 4}}, 4321.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 1}}), 5.0f);
	ASSERT_ALMOST_EQUAL(reshaped.get_idx(LogicalIndex{{0, 4}}), 4321.0f);
}

void test_reshape_rejects_multiple_negative_one(Device dev) {
	FloatTensor base = make_sequential_tensor({3, 4}, dev);
	bool threw = false;
	try {
		base.reshape({-1, -1});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_reshape_rejects_zero_and_negative_dims(Device dev) {
	FloatTensor base = make_sequential_tensor({3, 4}, dev);

	bool threw_zero = false;
	try {
		base.reshape({0, 12});
	} catch (const std::invalid_argument&) {
		threw_zero = true;
	}
	assert(threw_zero);

	bool threw_negative = false;
	try {
		base.reshape({-2, 6});
	} catch (const std::invalid_argument&) {
		threw_negative = true;
	}
	assert(threw_negative);
}

void test_reshape_rejects_invalid_numel(Device dev) {
	FloatTensor base = make_sequential_tensor({3, 4}, dev);
	bool threw = false;
	try {
		base.reshape({5, 5});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_expand_preserves_aliasing_and_uses_broadcast_strides(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 1, 3}, dev);
	FloatTensor expanded = source.expand({2, 4, -1});

	assert(expanded.shape_ == std::vector<size_t>({2, 4, 3}));
	assert(expanded.block_ == source.block_);
	assert(expanded.strides_ == std::vector<ssize_t>({3, 0, 1}));
	ASSERT_ALMOST_EQUAL(expanded.get_idx(LogicalIndex{{1, 0, 2}}), 6.0f);
	ASSERT_ALMOST_EQUAL(expanded.get_idx(LogicalIndex{{1, 3, 2}}), 6.0f);

	expanded.set_idx(LogicalIndex{{1, 2, 1}}, 99.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 0, 1}}), 99.0f);
	ASSERT_ALMOST_EQUAL(expanded.get_idx(LogicalIndex{{1, 0, 1}}), 99.0f);
	ASSERT_ALMOST_EQUAL(expanded.get_idx(LogicalIndex{{1, 3, 1}}), 99.0f);
}

void test_expand_noop_keeps_existing_strides(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev);
	FloatTensor expanded = source.expand({-1, 4});

	assert(expanded.shape_ == source.shape_);
	assert(expanded.strides_ == source.strides_);
	assert(expanded.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(expanded.get_idx(LogicalIndex{{2, 1}}),
	                    source.get_idx(LogicalIndex{{2, 1}}));
}

void test_expand_rejects_rank_mismatch(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 1, 3}, dev);
	bool threw = false;
	try {
		source.expand({2, 3});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_expand_rejects_non_singleton_dimension_change(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 1, 3}, dev);
	bool threw = false;
	try {
		source.expand({3, 4, 3});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_expand_rejects_invalid_non_placeholder_negative_dims(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 1, 3}, dev);

	bool threw_zero = false;
	try {
		source.expand({2, 0, 3});
	} catch (const std::invalid_argument&) {
		threw_zero = true;
	}
	assert(threw_zero);

	bool threw_negative = false;
	try {
		source.expand({2, -2, 3});
	} catch (const std::invalid_argument&) {
		threw_negative = true;
	}
	assert(threw_negative);
}

void test_unsqueeze_preserves_values_and_aliasing(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3}, dev);
	FloatTensor expanded_front = source.unsqueeze(0);
	FloatTensor expanded_back = source.unsqueeze(-1);

	assert(expanded_front.dim_ == 3);
	assert(expanded_front.shape_ == std::vector<size_t>({1, 2, 3}));
	assert(expanded_front.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(expanded_front.get_idx(LogicalIndex{{0, 1, 2}}),
	                    source.get_idx(LogicalIndex{{1, 2}}));

	expanded_front.set_idx(LogicalIndex{{0, 1, 2}}, 99.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 2}}), 99.0f);

	assert(expanded_back.dim_ == 3);
	assert(expanded_back.shape_ == std::vector<size_t>({2, 3, 1}));
	assert(expanded_back.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(expanded_back.get_idx(LogicalIndex{{1, 2, 0}}),
	                    source.get_idx(LogicalIndex{{1, 2}}));
}

void test_unsqueeze_preserves_contiguity(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3, 4}, dev);
	FloatTensor front = source.unsqueeze(0);
	FloatTensor middle = source.unsqueeze(1);
	FloatTensor back = source.unsqueeze(-1);

	assert(source.is_contiguous());
	assert(front.is_contiguous());
	assert(middle.is_contiguous());
	assert(back.is_contiguous());

	assert(front.shape_ == std::vector<size_t>({1, 2, 3, 4}));
	assert(middle.shape_ == std::vector<size_t>({2, 1, 3, 4}));
	assert(back.shape_ == std::vector<size_t>({2, 3, 4, 1}));
}

void test_squeeze_preserves_values_and_aliasing(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3}, dev).unsqueeze(1);
	FloatTensor squeezed = source.squeeze(1);
	FloatTensor squeezed_negative = source.squeeze(-2);

	assert(squeezed.dim_ == 2);
	assert(squeezed.shape_ == std::vector<size_t>({2, 3}));
	assert(squeezed.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(squeezed.get_idx(LogicalIndex{{1, 2}}),
	                    source.get_idx(LogicalIndex{{1, 0, 2}}));

	squeezed.set_idx(LogicalIndex{{1, 2}}, 77.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 0, 2}}), 77.0f);

	assert(squeezed_negative.shape_ == std::vector<size_t>({2, 3}));
	ASSERT_ALMOST_EQUAL(squeezed_negative.get_idx(LogicalIndex{{1, 2}}), 77.0f);
}

void test_squeeze_rejects_nonunit_dim(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3}, dev);
	bool threw = false;
	try {
		source.squeeze(1);
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_permute_reorders_axes_and_preserves_aliasing(Device dev) {
	FloatTensor source = make_sequential_tensor({3, 4, 5}, dev);
	FloatTensor permuted = source.permute({1, 2, 0});
	FloatTensor permuted_negative = source.permute({-2, -1, -3});

	assert(permuted.shape_ == std::vector<size_t>({4, 5, 3}));
	assert(permuted.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(permuted.get_idx(LogicalIndex{{1, 2, 0}}),
	                    source.get_idx(LogicalIndex{{0, 1, 2}}));

	permuted.set_idx(LogicalIndex{{1, 2, 0}}, 123.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{0, 1, 2}}), 123.0f);

	assert(permuted_negative.shape_ == std::vector<size_t>({4, 5, 3}));
	ASSERT_ALMOST_EQUAL(permuted_negative.get_idx(LogicalIndex{{1, 2, 0}}), 123.0f);
}

void test_transpose_swaps_axes_and_preserves_aliasing(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3, 4}, dev);
	FloatTensor transposed = source.transpose(0, 2);
	FloatTensor transposed_negative = source.transpose(-1, -3);

	assert(transposed.shape_ == std::vector<size_t>({4, 3, 2}));
	assert(transposed.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(transposed.get_idx(LogicalIndex{{3, 1, 1}}),
	                    source.get_idx(LogicalIndex{{1, 1, 3}}));

	transposed.set_idx(LogicalIndex{{3, 1, 1}}, 456.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 1, 3}}), 456.0f);

	assert(transposed_negative.shape_ == std::vector<size_t>({4, 3, 2}));
	ASSERT_ALMOST_EQUAL(transposed_negative.get_idx(LogicalIndex{{3, 1, 1}}), 456.0f);
}

void test_flatten_merges_dims_and_preserves_values(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3, 4}, dev);
	FloatTensor flattened = source.flatten(1, 2);

	assert(flattened.shape_ == std::vector<size_t>({2, 12}));
	assert(flattened.is_contiguous());
	ASSERT_ALMOST_EQUAL(flattened.get_idx(LogicalIndex{{1, 6}}),
	                    source.get_idx(LogicalIndex{{1, 1, 2}}));
	assert_raw_values(flattened, {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f,
	                            7.0f, 8.0f, 9.0f, 10.0f, 11.0f, 12.0f,
	                            13.0f, 14.0f, 15.0f, 16.0f, 17.0f, 18.0f,
	                            19.0f, 20.0f, 21.0f, 22.0f, 23.0f, 24.0f});
}

void test_flatten_noncontiguous_matches_contiguous_order(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev).unsqueeze(0);
	FloatTensor flattened = source.flatten(0, 1);

	assert(flattened.shape_ == std::vector<size_t>({3, 4}));
	assert(flattened.is_contiguous());
	assert_raw_values(flattened, {1.0f, 4.0f, 7.0f, 10.0f,
	                            2.0f, 5.0f, 8.0f, 11.0f,
	                            3.0f, 6.0f, 9.0f, 12.0f});
}

void test_contiguous_returns_self_for_contiguous_tensor(Device dev) {
	FloatTensor source = make_sequential_tensor({2, 3}, dev);
	FloatTensor contiguous = source.contiguous();

	assert(contiguous.shape_ == source.shape_);
	assert(contiguous.block_ == source.block_);
	ASSERT_ALMOST_EQUAL(contiguous.get_idx(LogicalIndex{{1, 2}}),
	                    source.get_idx(LogicalIndex{{1, 2}}));

	contiguous.set_idx(LogicalIndex{{1, 2}}, 321.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 2}}), 321.0f);
}

void test_contiguous_clones_noncontiguous_tensor(Device dev) {
	FloatTensor source = make_noncontiguous_tensor(dev);
	FloatTensor contiguous = source.contiguous();

	assert(contiguous.shape_ == source.shape_);
	assert(contiguous.is_contiguous());
	assert(contiguous.block_ != source.block_);
	assert_same_logical_values(source, contiguous);

	contiguous.set_idx(LogicalIndex{{1, 2}}, 654.0f);
	ASSERT_ALMOST_EQUAL(source.get_idx(LogicalIndex{{1, 2}}), 8.0f);
	ASSERT_ALMOST_EQUAL(contiguous.get_idx(LogicalIndex{{1, 2}}), 654.0f);
}

void run_layout_tests(Device dev) {
	test_contiguous_clone_preserves_shape_and_values(dev);
	test_contiguous_clone_breaks_aliasing(dev);
	test_reshape_contiguous_matches_flat_order(dev);
	test_reshape_noncontiguous_matches_contiguous_clone_then_reshape(dev);
	test_reshape_infers_negative_one(dev);
	test_reshape_always_copies_even_for_contiguous_tensor(dev);
	test_reshape_rejects_multiple_negative_one(dev);
	test_reshape_rejects_zero_and_negative_dims(dev);
	test_reshape_rejects_invalid_numel(dev);
	test_expand_preserves_aliasing_and_uses_broadcast_strides(dev);
	test_expand_noop_keeps_existing_strides(dev);
	test_expand_rejects_rank_mismatch(dev);
	test_expand_rejects_non_singleton_dimension_change(dev);
	test_expand_rejects_invalid_non_placeholder_negative_dims(dev);
	test_unsqueeze_preserves_values_and_aliasing(dev);
	test_unsqueeze_preserves_contiguity(dev);
	test_squeeze_preserves_values_and_aliasing(dev);
	test_squeeze_rejects_nonunit_dim(dev);
	test_permute_reorders_axes_and_preserves_aliasing(dev);
	test_transpose_swaps_axes_and_preserves_aliasing(dev);
	test_flatten_merges_dims_and_preserves_values(dev);
	test_flatten_noncontiguous_matches_contiguous_order(dev);
	test_contiguous_returns_self_for_contiguous_tensor(dev);
	test_contiguous_clones_noncontiguous_tensor(dev);
}

int main() {
	test_tensor_constructor();
	test_value_assignment();
	test_move();
	test_memory_not_wasted();
	test_copy_mutability();
	test_clone_mutability();
	test_view_shapes_strides_and_aliasing();
	test_view_of_view();
	test_view_memory_management();
	test_view_rejects_multiple_negative_one();
	test_view_rejects_zero_and_negative_dims();
	test_view_rejects_invalid_numel();
	test_view_rejects_noncontiguous_tensor();
	run_layout_tests(Device::CPU);
	run_layout_tests(Device::GPU);

	std::cout << "All tests passed."  << std::endl;
}
