#include <cuda_runtime.h>

#include <cstdio>
#include <cstdlib>
#include <iostream>
#include <cassert>
#include <cmath>
#include <memory>
#include <stdexcept>
#include <vector>

#include "cuda_utils.h"
#include "tensor.h"

// Not a good way to compare floats, it doesn't take scale into account...
// but good enough for us right now because all our values are O(1).
#define ASSERT_ALMOST_EQUAL(lhs, rhs) assert(std::abs((lhs) - (rhs)) < 0.0001);

size_t cuda_mem_free() {
	size_t mem_free, mem_total;
	CUDA_CHECK(cudaMemGetInfo(&mem_free, &mem_total));
	return mem_free;
}

void test_tensor_constructor() {
	FloatTensor t = FloatTensor::zeros_1d(10);
	float x = t.get_raw_idx(3);
	assert(x == 0.0f);
	return;
}

void test_value_assignment() {
	FloatTensor t = FloatTensor::zeros_1d(10);
	float val = 2.42;
	t.set_raw_idx(3, val);
	float should_be_val = t.get_raw_idx(3);
	assert(should_be_val == val);
	return;
}

void test_move() {
	FloatTensor t = FloatTensor::zeros_1d(2);
	t.set_raw_idx(0, 1.23);
	t.set_raw_idx(1, 4.56);

	t.move_to_device(Device::GPU);
	t.set_raw_idx(0, 2.34);
	float val0 = t.get_raw_idx(0);
	float val1 = t.get_raw_idx(1);
	ASSERT_ALMOST_EQUAL(val0, 2.34);
	ASSERT_ALMOST_EQUAL(val1, 4.56);

	t.move_to_device(Device::CPU);
	float val2 = t.get_raw_idx(0);
	float val3 = t.get_raw_idx(1);
	ASSERT_ALMOST_EQUAL(val2, 2.34);
	ASSERT_ALMOST_EQUAL(val3, 4.56);
	return;
}

void test_memory_not_wasted() {
	CUDA_CHECK(cudaGetLastError());
	CUDA_CHECK(cudaDeviceSynchronize());
	FloatTensor t = FloatTensor::zeros_1d(1000000);  // use lots of memory
	size_t mem_before = cuda_mem_free();
	t.move_to_device(Device::GPU);
	size_t mem_during = cuda_mem_free();
	t.move_to_device(Device::CPU);
	size_t mem_after = cuda_mem_free();
	assert(mem_after > mem_during);
	assert(mem_after == mem_before);
	return;
}

void test_copy_mutability() {
	FloatTensor t1 = FloatTensor::zeros_1d(2);
	FloatTensor t2 = t1;
	t1.set_raw_idx(0, 1.1);
	t2.set_raw_idx(1, 2.2);

	assert(t1.block_ == t2.block_);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(0), 1.1);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(1), 2.2);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(0), 1.1);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(1), 2.2);

	return;
}

void test_clone_mutability() {
	FloatTensor t1 = FloatTensor::zeros_1d(2);
	t1.set_raw_idx(0, 1.1);

	FloatTensor t2 = t1.clone();
	t2.set_raw_idx(1, 2.2);

	t1.set_raw_idx(0, 3.3);

	assert(t1.block_ != t2.block_);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(0), 3.3);
	ASSERT_ALMOST_EQUAL(t1.get_raw_idx(1), 0.0);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(0), 1.1);
	ASSERT_ALMOST_EQUAL(t2.get_raw_idx(1), 2.2);
	return;
}

// =========== TESTS GENERATED BY AI AGENTS ===========
void test_view_shapes_strides_and_aliasing() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);

	FloatTensor flat = base.view({12});
	assert(flat.dim_ == 1);
	assert(flat.shape_ == std::vector<size_t>({12}));
	assert(flat.strides_ == std::vector<ssize_t>({1}));
	assert(flat.block_ == base.block_);
	assert(flat.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(flat.get_idx(LogicalIndex{{6}}),
	                    base.get_idx(LogicalIndex{{1, 2}}));

	FloatTensor row = base.view({1, 12});
	assert(row.dim_ == 2);
	assert(row.shape_ == std::vector<size_t>({1, 12}));
	assert(row.strides_ == std::vector<ssize_t>({12, 1}));
	assert(row.block_ == base.block_);
	assert(row.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(row.get_idx(LogicalIndex{{0, 6}}),
	                    base.get_idx(LogicalIndex{{1, 2}}));

	FloatTensor reshaped = base.view({4, 3});
	assert(reshaped.dim_ == 2);
	assert(reshaped.shape_ == std::vector<size_t>({4, 3}));
	assert(reshaped.strides_ == std::vector<ssize_t>({3, 1}));
	assert(reshaped.block_ == base.block_);
	assert(reshaped.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(reshaped.get_idx(LogicalIndex{{2, 0}}),
	                    base.get_idx(LogicalIndex{{1, 2}}));
}

void test_view_of_view() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	FloatTensor first = base.view({1, 12});
	FloatTensor second = first.view({3, 4});

	assert(first.shape_ == std::vector<size_t>({1, 12}));
	assert(first.strides_ == std::vector<ssize_t>({12, 1}));
	assert(second.shape_ == std::vector<size_t>({3, 4}));
	assert(second.strides_ == std::vector<ssize_t>({4, 1}));
	assert(first.block_ == base.block_);
	assert(second.block_ == base.block_);
	assert(second.data_ptr() == base.data_ptr());
	ASSERT_ALMOST_EQUAL(second.get_idx(LogicalIndex{{2, 3}}),
	                    base.get_idx(LogicalIndex{{2, 3}}));

	FloatTensor third = first.view({12});
	assert(third.shape_ == std::vector<size_t>({12}));
	assert(third.strides_ == std::vector<ssize_t>({1}));
	assert(third.block_ == base.block_);
	ASSERT_ALMOST_EQUAL(third.get_idx(LogicalIndex{{11}}),
	                    base.get_idx(LogicalIndex{{2, 3}}));
}

void test_view_memory_management() {
	std::weak_ptr<FloatBlock> weak_block;
	std::unique_ptr<FloatTensor> last_view;

	{
		FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
		weak_block = base.block_;
		assert(base.block_.use_count() == 1);

		FloatTensor view1 = base.view({12});
		FloatTensor view2 = base.view({4, 3});
		assert(base.block_ == view1.block_);
		assert(base.block_ == view2.block_);
		assert(base.data_ptr() == view1.data_ptr());
		assert(base.data_ptr() == view2.data_ptr());
		assert(base.block_.use_count() == 3);

		last_view = std::make_unique<FloatTensor>(view2);
		assert(base.block_.use_count() == 4);
		ASSERT_ALMOST_EQUAL(last_view->get_idx(LogicalIndex{{2, 0}}),
		                    base.get_idx(LogicalIndex{{1, 2}}));
	}

	assert(!weak_block.expired());
	assert(last_view);
	assert(last_view->block_.use_count() == 1);
	float still_there = last_view->get_idx(LogicalIndex{{2, 0}});
	assert(std::isfinite(still_there));

	last_view.reset();
	assert(weak_block.expired());
}

void test_view_rejects_multiple_negative_one() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	bool threw = false;
	try {
		base.view({-1, -1});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_view_rejects_zero_and_negative_dims() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);

	bool threw_zero = false;
	try {
		base.view({0, 12});
	} catch (const std::invalid_argument&) {
		threw_zero = true;
	}
	assert(threw_zero);

	bool threw_negative = false;
	try {
		base.view({-2, 6});
	} catch (const std::invalid_argument&) {
		threw_negative = true;
	}
	assert(threw_negative);
}

void test_view_rejects_invalid_numel() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	bool threw = false;
	try {
		base.view({5, 5});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

void test_view_rejects_noncontiguous_tensor() {
	FloatTensor base = FloatTensor::randn({3, 4}, Device::CPU);
	FloatTensor noncontig = base.view_raw({3, 4}, 0, {1, 3});
	assert(!noncontig.is_contiguous());

	bool threw = false;
	try {
		noncontig.view({12});
	} catch (const std::invalid_argument&) {
		threw = true;
	}
	assert(threw);
}

int main() {
	test_tensor_constructor();
	test_value_assignment();
	test_move();
	test_memory_not_wasted();
	test_copy_mutability();
	test_clone_mutability();
	test_view_shapes_strides_and_aliasing();
	test_view_of_view();
	test_view_memory_management();
	test_view_rejects_multiple_negative_one();
	test_view_rejects_zero_and_negative_dims();
	test_view_rejects_invalid_numel();
	test_view_rejects_noncontiguous_tensor();

	std::cout << "All tests passed."  << std::endl;
}
